# Generated by Django 2.2.10 on 2020-03-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0008_auto_20190221_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageHourAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
                ('dow', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('camera_id', models.CharField(max_length=255)),
                ('camera_naam', models.CharField(max_length=255)),
                ('rijrichting', models.IntegerField()),
                ('camera_kijkrichting', models.FloatField()),
                ('kenteken_land', models.TextField()),
                ('voertuig_soort', models.CharField(max_length=25)),
                ('europese_voertuigcategorie', models.CharField(max_length=2)),
                ('taxi_indicator', models.BooleanField()),
                ('diesel', models.IntegerField(null=True)),
                ('gasoline', models.IntegerField(null=True)),
                ('electric', models.IntegerField(null=True)),
                ('toegestane_maximum_massa_voertuig', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
