# Generated by Django 2.2.10 on 2020-04-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0009_passagehouraggregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='europese_voertuigcategorie',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='taxi_indicator',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='voertuig_soort',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
