# Generated by Django 2.2.20 on 2021-05-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0011_passage_minute_view_v1_20200708_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='privacy_check',
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
