# Generated by Django 2.2.20 on 2021-08-19 12:57
import django.contrib.gis.db.models.fields
from datetimeutc.fields import DateTimeUTCField
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0013_remove_passage_privacy_check'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='ZoneZwaarVerkeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_at_timestamp', DateTimeUTCField()),
                ('passage_at_date', models.DateField()),
                ('passage_at_year', models.IntegerField()),
                ('passage_at_month', models.IntegerField()),
                ('passage_at_day', models.IntegerField()),
                ('passage_at_week', models.IntegerField()),
                ('passage_at_day_of_week', models.CharField(max_length=20)),
                ('passage_at_hour', models.IntegerField()),
                ('order_kaart', models.IntegerField(blank=True, null=True)),
                ('order_naam', models.CharField(blank=True, max_length=255, null=True)),
                ('cordon', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('richting', models.CharField(blank=True, max_length=3, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geom', models.CharField(blank=True, max_length=255, null=True)),
                ('azimuth', models.FloatField()),
                ('kenteken_land', models.TextField()),
                ('voertuig_soort', models.CharField(max_length=25, null=True)),
                ('inrichting', models.CharField(max_length=255, null=True)),
                ('voertuig_klasse_toegestaan_gewicht', models.CharField(blank=True, max_length=255, null=True)),
                ('intensiteit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZwaarVerkeerHelperTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_naam', models.CharField(db_index=True, max_length=255)),
                ('rijrichting', models.IntegerField(blank=True, db_index=True, null=True)),
                ('camera_kijkrichting', models.FloatField(blank=True, db_index=True, null=True)),
                ('order_kaart', models.IntegerField(blank=True, null=True)),
                ('order_naam', models.CharField(blank=True, max_length=255, null=True)),
                ('cordon', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('richting', models.CharField(blank=True, max_length=10, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geom', models.CharField(blank=True, max_length=255, null=True)),
                ('azimuth', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
