# Generated by Django 2.2.20 on 2021-08-19 09:57
import csv
import os

from django.conf import settings
from django.contrib.gis.geos import Point
from django.db import migrations, transaction


def import_helper_table(apps, schema_editor):
    ZwaarVerkeerHelperTable = apps.get_model('passage', 'ZwaarVerkeerHelperTable')

    helper_table_csv_path = os.path.join(
        settings.BASE_DIR, 'passage', 'helpertable.csv'
    )

    with transaction.atomic():
        ZwaarVerkeerHelperTable.objects.all().delete()

        with open(helper_table_csv_path, newline='') as csvfile:
            reader = csv.DictReader(csvfile, dialect='excel', delimiter=',')

            inserts = []
            for row in reader:
                for key in row.keys():
                    row[key] = None if row[key] == '' else row[key]

                row['location'] = Point(
                    float(row.pop('latitude')), float(row.pop('longitude')), srid=4326
                )
                inserts.append(ZwaarVerkeerHelperTable(**row))

        ZwaarVerkeerHelperTable.objects.bulk_create(inserts)


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0014_zonezwaarverkeer_zwaarverkeerhelpertable'),
    ]

    operations = [migrations.RunPython(import_helper_table, migrations.RunPython.noop)]
