# Generated by Django 2.2.24 on 2021-09-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0015_auto_20210819_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZwaarVerkeerHelperTable',
            new_name='Camera',
        ),
        migrations.RenameModel(
            old_name='ZoneZwaarVerkeer',
            new_name='HeavyTrafficHourAggregation',
        ),
    ]
