# Generated by Django 2.2.24 on 2021-09-20 09:44

import datetimeutc.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0016_auto_20210909_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGORHourAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_at_timestamp', datetimeutc.fields.DateTimeUTCField()),
                ('passage_at_date', models.DateField()),
                ('passage_at_year', models.IntegerField()),
                ('passage_at_month', models.IntegerField()),
                ('passage_at_day', models.IntegerField()),
                ('passage_at_week', models.IntegerField()),
                ('passage_at_day_of_week', models.CharField(max_length=20)),
                ('passage_at_hour', models.IntegerField()),
                ('order_kaart', models.IntegerField(blank=True, null=True)),
                ('order_naam', models.CharField(blank=True, max_length=255, null=True)),
                ('cordon', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('richting', models.CharField(blank=True, max_length=3, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geom', models.CharField(blank=True, max_length=255, null=True)),
                ('azimuth', models.FloatField()),
                ('kenteken_land', models.TextField()),
                ('intensiteit', models.IntegerField(blank=True, null=True)),
                ('taxi_indicator', models.NullBooleanField()),
                ('europese_voertuigcategorie', models.CharField(max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
