# Generated by Django 2.2.24 on 2021-09-14 11:03

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0016_auto_20210909_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageCamera',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('straat', models.CharField(max_length=255, null=True)),
                ('rijrichting', models.SmallIntegerField()),
                ('rijstrook', models.SmallIntegerField()),
                ('camera_id', models.CharField(max_length=255)),
                ('camera_naam', models.CharField(max_length=255)),
                ('camera_kijkrichting', models.FloatField()),
                ('camera_locatie', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassageVehicle',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('kenteken_land', models.CharField(max_length=2)),
                ('voertuig_soort', models.CharField(max_length=25, null=True)),
                ('merk', models.CharField(max_length=255, null=True)),
                ('inrichting', models.CharField(max_length=255, null=True)),
                ('datum_eerste_toelating', models.DateField(null=True)),
                ('datum_tenaamstelling', models.DateField(null=True)),
                ('toegestane_maximum_massa_voertuig', models.IntegerField(null=True)),
                ('europese_voertuigcategorie', models.CharField(max_length=2, null=True)),
                ('europese_voertuigcategorie_toevoeging', models.CharField(max_length=1, null=True)),
                ('taxi_indicator', models.NullBooleanField()),
                ('maximale_constructie_snelheid_bromsnorfiets', models.SmallIntegerField(null=True)),
                ('brandstoffen', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('diesel', models.SmallIntegerField(null=True)),
                ('gasoline', models.SmallIntegerField(null=True)),
                ('electric', models.SmallIntegerField(null=True)),
                ('versit_klasse', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
