# Generated by Django 2.2.24 on 2021-09-21 11:38

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import passage.models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0016_auto_20210909_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=40, unique=True)),
                ('straat', models.CharField(max_length=255, null=True)),
                ('rijrichting', models.SmallIntegerField()),
                ('rijstrook', models.SmallIntegerField()),
                ('camera_id', models.CharField(max_length=255)),
                ('camera_naam', models.CharField(max_length=255)),
                ('camera_kijkrichting', models.FloatField()),
                ('camera_locatie', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassageVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=40, unique=True)),
                ('kenteken_land', models.CharField(max_length=2)),
                ('voertuig_soort', models.CharField(max_length=25, null=True)),
                ('merk', models.CharField(max_length=255, null=True)),
                ('inrichting', models.CharField(max_length=255, null=True)),
                ('datum_eerste_toelating', models.DateField(null=True)),
                ('datum_tenaamstelling', models.DateField(null=True)),
                ('toegestane_maximum_massa_voertuig', models.IntegerField(null=True)),
                ('europese_voertuigcategorie', models.CharField(max_length=2, null=True)),
                ('europese_voertuigcategorie_toevoeging', models.CharField(max_length=1, null=True)),
                ('taxi_indicator', models.NullBooleanField()),
                ('maximale_constructie_snelheid_bromsnorfiets', models.SmallIntegerField(null=True)),
                ('automatisch_verwerkbaar', models.NullBooleanField()),
                ('brandstoffen', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('diesel', models.SmallIntegerField(null=True)),
                ('gasoline', models.SmallIntegerField(null=True)),
                ('electric', models.SmallIntegerField(null=True)),
                ('versit_klasse', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='passage',
            name='automatisch_verwerkbaar',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='brandstoffen',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='camera_id',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='camera_kijkrichting',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='camera_locatie',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='camera_naam',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='datum_eerste_toelating',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='datum_tenaamstelling',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='diesel',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='electric',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='europese_voertuigcategorie',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='europese_voertuigcategorie_toevoeging',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='gasoline',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='inrichting',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='kenteken_karakters_betrouwbaarheid',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='kenteken_land',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='maximale_constructie_snelheid_bromsnorfiets',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='merk',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='rijrichting',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='rijstrook',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='straat',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='taxi_indicator',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='toegestane_maximum_massa_voertuig',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='versit_klasse',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='voertuig_soort',
        ),
        migrations.AlterField(
            model_name='passage',
            name='kenteken_land_betrouwbaarheid',
            field=passage.models.BetrouwbaarheidField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passage',
            name='kenteken_nummer_betrouwbaarheid',
            field=passage.models.BetrouwbaarheidField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='passage',
            name='passage_camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='passage.PassageCamera'),
        ),
        migrations.AddField(
            model_name='passage',
            name='passage_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='passage.PassageVehicle'),
        ),
    ]
