# Generated by Django 2.2.24 on 2021-09-21 09:02

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations
import passage.models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0017_auto_20210921_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='kenteken_karakters_betrouwbaarheid',
            field=django.contrib.postgres.fields.ArrayField(base_field=passage.models.BetrouwbaarheidField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]), null=True, size=None),
        ),
    ]
