# Generated by Django 2.2.24 on 2021-09-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0017_passagecamera_passagevehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='passage_camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='passage.PassageCamera'),
        ),
        migrations.AddField(
            model_name='passage',
            name='passage_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='passage.PassageVehicle'),
        ),
    ]
