# Generated by Django 2.2.24 on 2021-09-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0018_add_foreign_keys_to_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='brandstoffen',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='camera_id',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='camera_kijkrichting',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='camera_locatie',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='camera_naam',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='datum_eerste_toelating',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='datum_tenaamstelling',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='diesel',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='electric',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='europese_voertuigcategorie',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='europese_voertuigcategorie_toevoeging',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='gasoline',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='inrichting',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='kenteken_land',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='maximale_constructie_snelheid_bromsnorfiets',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='merk',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='rijrichting',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='rijstrook',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='straat',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='taxi_indicator',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='toegestane_maximum_massa_voertuig',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='versit_klasse',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='voertuig_soort',
        ),
    ]
